name: mdenv
channels:
  - omnia
  - plotly
  - conda-forge
dependencies:
  - openmm=8.0.0
  - openmmforcefields=0.11.2
  - pdbfixer=1.9
  - rdkit=2023.03.1
  - mdtraj=1.9.9
  - plotly=4.9.0
  - python-kaleido=0.2.1
  - mdanalysis=2.5.0
  - prody=2.4.0
- pip:
  - openbabel==3.1.1
